### ISSUE TITLE
increase embedded table 

### ISSUE THREAD

**Issue by johav** [AfricArxiv/info.africarxiv.org#27]
- https://info.africarxiv.org/submit/

Please also write a short description how to do that and place it in the repo :)

**Comment by JustinyAhin** [comment]
- [ ]  increase embedded table

- [ ]  write a short description how to do that and place it in the repo :)

**Comment by johav** [comment]
can you add the info here: https://github.com/AfricArxiv/info.africarxiv.org/blob/master/embedding-files-in-wp.md @JustinyAhin  ?
