### ISSUE TITLE
Footer update

### ISSUE THREAD

**Issue by johav** [AfricArxiv/info.africarxiv.org#30]
embed images for having signed the following two declarations

AfricArXiv is a Signatory of [sfDORA](https://sfdora.org/read/) and the [Helsinki Initiative on Multilingualism in Scholarly Communication](https://www.helsinki-initiative.org/en)

- [x] https://sfdora.org/2018/06/15/dora-announces-badges-for-signatories/
- [x] https://www.helsinki-initiative.org/en/info

**Comment by JustinyAhin** [comment]
Do you mean embedding them on info.africarxiv.org footer?

**Comment by JustinyAhin** [comment]
The sfDora logo is on the about https://info.africarxiv.org/about

**Comment by johav** [comment]
Yes please - add the pics to the footer for better visibility, adding this sentence:

AfricArXiv is a Signatory of sfDORA and the Helsinki Initiative on Multilingualism in Scholarly Communication.

**Comment by johav** [comment]
thanks for adding the logos. it's now in a separate section, right? Is it possible to add the logos in the footer or not?
Please add the sentence: AfricArXiv is a Signatory of [sfDORA](https://sfdora.org/read/) and the [Helsinki Initiative](https://www.helsinki-initiative.org/en).
