### ISSUE TITLE
kiSwahili translation correction on website

### ISSUE THREAD

**Issue by johav** [AfricArxiv/info.africarxiv.org#35]
Check the website www.africarxiv.org for correct translations from English to kiSwahili.

- [x] Frontpage
- [x] Menu // navigation bar
- [x] subpages

GTranslate guideline how to edit translations on the website: https://docs.gtranslate.io/en/articles/1348921-how-to-edit-translations

**Comment by Johanssen** [comment]
This is completed now. It was interesting and helped me interact more with my language.

**Comment by Johanssen** [comment]
@Johanssen can you check if this works? https://github.com/AfricArxiv/languages/blob/master/website-translations.md // as a description how to edit the text

This link seems to be broken.
